<font size = "6">PROGRAM - 1</font><br><br><br>
<center><font size = "3">Arrays and Metrices</font></center><br><br>


<font size = "6">(A) : Create arrays with specific values:</font>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#(i) array of all ones
a1=np.ones(6)

In [3]:
a1

array([1., 1., 1., 1., 1., 1.])

In [4]:
#(ii) array of all zeros
a2= np.zeros(6)

In [5]:
a2

array([0., 0., 0., 0., 0., 0.])

In [6]:
#(iii) array with random values within a range
a3 = np.random.randint(1,20,9)

In [7]:
a3

array([ 2, 18, 14,  4, 12, 18, 14,  7, 10])

In [8]:
#(iv) a diagonal matrix
diagonal_mat = np.eye(4)

In [9]:
diagonal_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<font size = "6">(B) : Perform other matrix operations:</font>

In [10]:
arr1 = np.array([1,2,-3,4,6,-1,3,8,3]).reshape(3,3)

In [11]:
arr1

array([[ 1,  2, -3],
       [ 4,  6, -1],
       [ 3,  8,  3]])

In [12]:
#(i) convert matrix data to absolute values
matrix1 = np.absolute(arr1)

In [13]:
matrix1

array([[1, 2, 3],
       [4, 6, 1],
       [3, 8, 3]])

In [14]:
#(ii) convert matrix data to negative values
matrix2 = np.negative(arr1)

In [15]:
matrix2

array([[-1, -2,  3],
       [-4, -6,  1],
       [-3, -8, -3]])

In [16]:
#(iii) add rows & columns from a matrix
matrix3 = np.append(arr1, matrix2, axis = 0)

In [17]:
matrix3

array([[ 1,  2, -3],
       [ 4,  6, -1],
       [ 3,  8,  3],
       [-1, -2,  3],
       [-4, -6,  1],
       [-3, -8, -3]])

In [18]:
#(iv) remove rows & colums from a matrix
    #delete 1st row
data = np.delete(matrix3, 1, 0)
print("data after 1st row deleted : ", data)

data after 1st row deleted :  [[ 1  2 -3]
 [ 3  8  3]
 [-1 -2  3]
 [-4 -6  1]
 [-3 -8 -3]]


In [19]:
    #delete 0th column
data = np.delete(matrix3, 0, 1)
print("data after 0th column deleted : ", data)

data after 0th column deleted :  [[ 2 -3]
 [ 6 -1]
 [ 8  3]
 [-2  3]
 [-6  1]
 [-8 -3]]


In [20]:
#(v) find the maximum and minimum values in a matrix or in a row/column
matrix2

array([[-1, -2,  3],
       [-4, -6,  1],
       [-3, -8, -3]])

In [21]:
matrix2.max() #maximum value

3

In [22]:
matrix2.min() #minimum value

-8

In [23]:
#(vi) find the sum of all/some elements in a matrix
total = np.sum(matrix2)
total

-23