<font size = "6">PROGRAM - 2</font><br><br><br>
<center><font size = "3">File Handling</font></center><br><br>

In [2]:
import numpy as np
import pandas as pd

<font size = "6">(A) : Load data from a text file (file should contain matrix data)</font>

In [7]:
#Text file data converted to integer data type
File_data = np.loadtxt("f2.txt", dtype = int)
print(File_data)

[[13 12  9]
 [ 8 25 14]
 [20  6  8]]


<font size = "6">(B) : Use commands to compute the : </font>

In [8]:
#(i)Size of Matrix
len(File_data)

3

In [9]:
#(ii)Size/length of a particular row/column

In [10]:
#Size of 1st column
len(File_data[:,1])

3

In [11]:
#Size of Zeroth Row
len(File_data[0])

3

<font size = "6">(C) : Store matrix data to a text file </font>

In [12]:
d1 = np.random.randint(1,20,9).reshape(3,3)
d1

array([[16, 12, 15],
       [11,  1,  1],
       [10, 12,  3]])

In [13]:
np.savetxt("f2c.txt", d1)

In [14]:
content = np.loadtxt('f2c.txt')
print("\nContent in file1.txt:\n", content)


Content in file1.txt:
 [[16. 12. 15.]
 [11.  1.  1.]
 [10. 12.  3.]]
