<font size = "6">PROGRAM - 3</font><br><br><br>
<center><font size = "3">Matrices</font></center><br><br>

In [1]:
import numpy as np
import pandas as pd

<font size = "6">(A) : Perform basic operation on matrices:</font>

In [2]:
matrix1 = np.random.randint(2,20,9).reshape(3,3)

In [3]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)

In [4]:
matrix1

array([[ 6, 13, 10],
       [18,  8,  3],
       [13,  2,  8]])

In [5]:
matrix2

array([[8, 5, 8],
       [1, 1, 1],
       [3, 3, 9]])

In [7]:
#(i) addition of 2 matrices
matrix3 = matrix1+matrix2

In [8]:
matrix3

array([[14, 18, 18],
       [19,  9,  4],
       [16,  5, 17]])

In [9]:
#(ii) subtraction of 2 matrices
matrix4 = matrix1-matrix2

In [10]:
matrix4

array([[-2,  8,  2],
       [17,  7,  2],
       [10, -1, -1]])

In [11]:
#(iii) Multiplication of 2 matrices
matrix5 = matrix1*matrix2

In [12]:
matrix5

array([[48, 65, 80],
       [18,  8,  3],
       [39,  6, 72]])

In [13]:
#(iv) Transpose of matrices
matrix6 = np.transpose(matrix5)

In [14]:
matrix6

array([[48, 18, 39],
       [65,  8,  6],
       [80,  3, 72]])

<font size = "6">(B) : Display specific rows or column of a matrix</font>

In [15]:
matrix7 = np.random.randint(2,100,36).reshape(6,6)

In [16]:
matrix7

array([[27, 94, 55,  8,  8, 19],
       [18, 85, 13, 47, 31, 80],
       [70, 73, 17, 44, 86, 51],
       [75, 97,  6, 49, 67, 88],
       [22, 13, 75, 77, 21, 22],
       [60, 86, 98, 27, 93,  2]])

In [18]:
#Specific rows and columns
print(matrix7[0:2,1:5])

[[94 55  8  8]
 [85 13 47 31]]
